query questionData($titleSlug: String!) {
  question(titleSlug: $titleSlug) {
    questionFrontendId
    title
    titleSlug
    content
    isPaidOnly
    difficulty
    topicTags {
      name
    }
    hints
  }
}
