query solutions(
  $questionSlug: String!
  $skip: Int!
  $first: Int!
  $query: String
  $orderBy: TopicSortingOption
  $languageTags: [String!]
) {
  questionSolutions(
    filters: {
      questionSlug: $questionSlug
      skip: $skip
      first: $first
      query: $query
      orderBy: $orderBy
      languageTags: $languageTags
    }
  ) {
    solutions {
      title
      post {
        id
        voteCount
      }
    }
  }
}
